- Code/Public/Test-TppObjectExist.ps1
initial cut of this script, needs testing
> Test-TppObjectExist

- VenafiTppPS/Enums/WorkflowResult.ps1
- VenafiTppPS/Public/Get-TppWorkflowDetail.ps1
- VenafiTppPS/Public/Set-TppAttribute.ps1
- VenafiTppPS/VenafiTppPS.psd1
- build/psake.ps1
- add ability to get workflow ticket details by DN or Guid
- update for #32 
- fix #33 
- !deploy
> Workflow basics and more and !deploy

- RELEASE.md
- VenafiTppPS/Public/Invoke-TppCertificateRenewal.ps1
- VenafiTppPS/Public/New-TppCertificate.ps1
- minor updates to cert renewal
- basic certificate creation functionality added
> Basic cert creation functionality and !deploy

- RELEASE.md
- VenafiTppPS/Public/Invoke-TppCertificateRevocation.ps1
> add certificate revocation and !deploy

- RELEASE.md
- VenafiTppPS/Public/New-TppPolicy.ps1
- VenafiTppPS/Public/Restore-TppCertificate.ps1
- VenafiTppPS/Public/Revoke-TppCertificate.ps1
- add support for new policy folder creation
- rename functions
> Rename functions, add support for new policy folder creation and !deploy

- RELEASE.md
- VenafiTppPS/Code/Enums/CertificateStage.ps1
- VenafiTppPS/Code/Private/Get-EnumValues.ps1
- VenafiTppPS/Code/Public/Get-TppCertificateDetail.ps1
- add status filters to Get-TppCertificateDetail, all filters added
- certificate stage enum added
- Get-EnumValues function added
> add status filters to Get-TppCertificateDetail

- VenafiTppPS/Code/Public/Get-TppCertificateDetail.ps1
> SanDns option had a misspelling

- RELEASE.md
- VenafiTppPS/Code/Public/Get-TppIdentity.ps1
- VenafiTppPS/Code/Public/Get-TppIdentityAttribute.ps1
- VenafiTppPS/Code/Public/Get-TppPermission.ps1
- add Get-TppIdentityAttribute
- update Get-TppPermission
- add Explicit/Implicit permissions in addition to Effective
- utilize Prefixed Universal ID
- add ability to retrieve identity attribute values
> update Get-TppPermission, add Get-TppIdentityAttribute

- RELEASE.md
- VenafiTppPS/Code/Public/Get-TppObject.ps1
Get-TppObject needed to be refactored due to inaccurate parameter sets
> refactor Get-TppObject

- build/Set-ModuleMetadata.ps1
import by psd as opposed to psm to pull in classes
> fix build issues

- RELEASE.md
- VenafiTppPS/Code/Classes/TppSession.ps1
- VenafiTppPS/Code/Private/Invoke-TppRestMethod.ps1
- VenafiTppPS/Code/Public/Get-TppSystemStatus.ps1
- Rolling back version checking from 0.7.3 due to possible bug with API method /SystemStatus
> revert version checking

- VenafiTppPS/Code/Public/Add-TppCertificateAssociation.ps1
- VenafiTppPS/Code/Public/New-TppCapiApplication.ps1
- VenafiTppPS/Code/Public/New-TppObject.ps1
- VenafiTppPS/Code/VenafiTppPS.psd1
- add Add-TppCertificateAssociation to associate a certificate to one or more application objects
- update New-TppObject to use Add-TppCertificateAssociation when a certificate is provided
- update New-TppCapiApplication to use the updated New-TppObject
> cert-app association updates

- RELEASE.md
- VenafiTppPS/Code/Public/Get-TppIdentityAttribute.ps1
update validation in Get-TppIdentityAttribute to validate existence as well as format
> Identity validation update

- RELEASE.md
- VenafiTppPS/Code/Public/New-TppCertificate.ps1
add parameter for Subject Alternate Names to New-TppCertificate
> Add SAN to New-TppCertificate

- RELEASE.md
- VenafiTppPS/Code/Public/Find-TppCertificate.ps1
- VenafiTppPS/Code/Public/Get-TppAttribute.ps1
- VenafiTppPS/Code/Public/Get-TppCertificateDetail.ps1
- VenafiTppPS/Code/Public/Get-TppIdentityAttribute.ps1
- VenafiTppPS/Code/Public/Get-TppPermission.ps1
- VenafiTppPS/Code/Public/Get-TppWorkflowTicket.ps1
- VenafiTppPS/Code/Public/Move-TppObject.ps1
- VenafiTppPS/Code/Public/New-TppCapiApplication.ps1
- VenafiTppPS/Code/Public/New-TppCertificate.ps1
- VenafiTppPS/Code/Public/New-TppObject.ps1
- VenafiTppPS/Code/Public/New-TppPolicy.ps1
- VenafiTppPS/Code/Public/Remove-TppCertificate.ps1
- VenafiTppPS/Code/Public/Remove-TppCertificateAssociation.ps1
- VenafiTppPS/Code/Public/Rename-TppObject.ps1
- VenafiTppPS/Code/Public/Revoke-TppCertificate.ps1
- VenafiTppPS/Code/Public/Set-TppPermission.ps1
- VenafiTppPS/Code/VenafiTppPS.psd1
- fix session state not being preserved across internal function calls, thanks Kory B!
- add Pipeline and ShouldProcess support to New-TppPolicy
- add ShouldProcess support to New-TppObject
> New object creation updates, session fix

- RELEASE.md
- VenafiTppPS/Code/Public/Add-TppCertificateAssociation.ps1
fix provision cert not working in New-TppObject, #89
> fix provision cert not working

- CHANGELOG.md
- VenafiTppPS/Code/Public/Invoke-TppRestMethod.ps1
- VenafiTppPS/Code/Public/Write-TppLog.ps1
Resolve #114 due to header getting stripped
> Write-TppLog header getting stripped

- CHANGELOG.md
- VenafiTppPS/Code/Public/Get-TppPermission.ps1
- VenafiTppPS/Code/VenafiTppPS.psd1
> Get-TppPermission fixes

- VenafiTppPS/Code/Public/Revoke-TppToken.ps1
> Fix confirmation target when running Revoke-TppToken

- VenafiTppPS/Code/Classes/TppSession.ps1
- VenafiTppPS/Code/VenafiTppPS.psd1
folks are still downloading the old project so I'm making the messaging a bit more apparent.
> new project messaging
